name: Receive Tag

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag Name"
        required: true

jobs:
  process-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository B
        uses: actions/checkout@v2

      - name: Print received tag
        run: |
          echo "Received Tag: ${{ github.event.inputs.tag }}"

      - name: Trigger SendGrid Workflow
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'trigger-sendgrid',
              client_payload: {
                tag: '${{ github.event.inputs.tag }}'
              },
              headers: {
                'Authorization': 'Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}'
              }
            })
